### ISSUE TITLE
Allow for different element types

### ISSUE THREAD

**Issue by nrempel** [ccnokes/react-toggle-display#2]
What do you think about allowing different element types?

Something like
```
<ToggleDisplay show={this.state.isAuthorized} type='button'>
  <p>Secret stuff for authorized people only.</p>
</ToggleDisplay>
```

So that elements don't need to be all wrapped in a span?

**Comment by ccnokes** [comment]
I could consider it.... But why not just wrap a <button> in a ToggleDisplay
element?

**Comment by nrempel** [comment]
The issue I ran into was in a table.

I want to conditionally hide/show `td` elements in a table. When a `span` appears as a child element of a `tr`, react gets mad.

If you're open to it, I can try to create a PR. Can't guarantee I'll have time soon though.

Thanks for the handy lib!

**Comment by ccnokes** [comment]
Gotcha, that makes sense. Yeah, a PR would be awesome. I'm a little busy
but maybe I'll get to it sometime this month or next. Thanks for bringing
this up!

**Comment by nrempel** [comment]
Thanks!

On Tue, Apr 19, 2016 at 7:41 PM, Cameron Nokes <notifications@github.com> wrote:
Gotcha, that makes sense. Yeah, a PR would be awesome. I'm a little busy
but maybe I'll get to it sometime this month or next. Thanks for bringing
this up!
