### ISSUE TITLE
Warning: Unknown prop 'show' on <span> tag

### ISSUE THREAD

**Issue by ammichael** [ccnokes/react-toggle-display#3]
Hello there!

Really nice component! Thanks

I've just tried it out and works like a charm, but I keep receiving this warning:

![image](https://cloud.githubusercontent.com/assets/6873880/17684432/ff056d02-6331-11e6-88e6-30c1511d6c64.png)

Any idea why?

Thanks again!

**Comment by ccnokes** [comment]
I just released an update that broke it 😰. A fix is coming soon 😸

**Comment by ccnokes** [comment]
@ammichael try it again, it should be fixed. Thanks for reporting it 👍

**Comment by ammichael** [comment]
Everything is working fine now. Seriously, thanks for this awesome component! 😄
